{
 "title": "LMD",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(lmd_info, instance)"
   },
   {
    "name": "types",
    "query": "label_values(lmd_peer_object_count,type)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected Sites",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by(instance) (lmd_peer_backend_connections{instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total Cached Objects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lmd_peer_object_count{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "lmd_info{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Ressource Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_goroutines{instance=~\"$instance\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "go routines",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=~\"$instance\"}[15s])) * 100",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "cpu %",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(process_open_fds{instance=~\"$instance\"})",
     "legendFormat": "open fd"
    },
    {
     "expr": "sum(process_resident_memory_bytes{instance=~\"$instance\"})",
     "legendFormat": "res memory"
    },
    {
     "expr": "sum(process_virtual_memory_bytes{instance=~\"$instance\"})",
     "legendFormat": "virt memory"
    }
   ]
  },
  {
   "title": "Cached Objects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(peer)(lmd_peer_object_count{instance=~\"$instance\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{peer}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avergage Bytes per Object",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{instance=~\"$instance\"})/(sum(lmd_peer_object_count{instance=~\"$instance\"}))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "avg bytes per object",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traffic Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontend Traffic",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg by(listen)(rate(lmd_frontend_send_bytes{instance=~\"$instance\"}[1m]))",
       "legendFormat": "send {{listen}}"
      },
      {
       "expr": "avg by(listen)(rate(lmd_frontend_received_bytes{instance=~\"$instance\"}[1m]))",
       "legendFormat": "received {{listen}}"
      }
     ]
    },
    {
     "title": "Frontend Queries",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(listen)(rate(lmd_frontend_queries{instance=~\"$instance\"}[1m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Queries {{listen}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Frontend Connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(listen)(rate(lmd_frontend_connections{instance=~\"$instance\"}[1m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Connections {{listen}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Backend Traffic",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg by(peer)(rate(lmd_peer_received_bytes{instance=~\"$instance\"}[1m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Received {{peer}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "avg by(peer)(rate(lmd_peer_sent_bytes{instance=~\"$instance\"}[1m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Send {{peer}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "lmd_peer_update_interval{instance=~\"$instance\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Update Interval",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Backend Queries",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(peer)(rate(lmd_peer_backend_queries{instance=~\"$instance\"}[1m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Queries {{peer}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Backend Connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(peer)(rate(lmd_peer_backend_connections{instance=~\"$instance\"}[1m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Connections {{peer}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "avg by(peer)(rate(lmd_peer_backend_failed_connections{instance=~\"$instance\"}[1m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Failed {{peer}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Backend Response Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by(peer)(lmd_peer_update_duration_seconds{instance=~\"$instance\"})",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Response Time {{peer}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Updated Objects Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "rowsps" } },
     "targets": [
      {
       "expr": "avg by(peer)(rate(lmd_peer_updated_objects{instance=~\"$instance\"}[1m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{peer}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Object Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cached $types",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 168 },
     "repeat": "types",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(peer)(lmd_peer_object_count{instance=~\"$instance\",type=\"$types\"})",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{peer}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "process memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(process_resident_memory_bytes{instance=~\"$instance\"})",
       "legendFormat": "resident"
      },
      {
       "expr": "sum(process_virtual_memory_bytes{instance=~\"$instance\"})",
       "legendFormat": "virtual"
      }
     ]
    },
    {
     "title": "go memstats",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(go_memstats_alloc_bytes{instance=~\"$instance\"})",
       "legendFormat": "bytes allocated"
      },
      {
       "expr": "sum(rate(go_memstats_alloc_bytes_total{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "alloc rate"
      },
      {
       "expr": "sum(go_memstats_stack_inuse_bytes{instance=~\"$instance\"})",
       "legendFormat": "stack inuse"
      },
      {
       "expr": "sum(go_memstats_heap_inuse_bytes{instance=~\"$instance\"})",
       "legendFormat": "heap inuse"
      }
     ]
    },
    {
     "title": "string deduplication",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(lmd_string_dedup_bytes{instance=~\"$instance\"})",
       "legendFormat": "cache size"
      },
      {
       "expr": "sum(lmd_string_dedup_count{instance=~\"$instance\"})",
       "legendFormat": "cache entries"
      }
     ]
    }
   ]
  }
 ]
}