#!/bin/bash
#
# This script determines the Linux distribution we are running
# on. It output two words: (1) The distro name and (2) the version
# Example output "UBUNTU 10.04"

# Ubuntu is detected with /etc/lsb-release
SEP=${1:- }
if [ -e /etc/lsb-release ] 
then
    . /etc/lsb-release
    if [ -n "$DISTRIB_ID" -a -n "$DISTRIB_RELEASE" ] ; then
        echo "${DISTRIB_ID^^*}$SEP$DISTRIB_RELEASE"
        exit 0
    fi
fi

# Debian: We drop the last version: 5.0.4 -> 5.0
if [ -e /etc/debian_version ]
then
    VERSION=$(cat /etc/debian_version)
    if [ "${VERSION:3:1}" = . ] ; then
        VERSION=${VERSION:0:3}
    fi
    echo "DEBIAN$SEP$VERSION"
    exit 0
fi

# RedHat / CentOS
if [ -e /etc/redhat-release ]
then
    # CentOS release 5.4 (Final)
    VERSION=$(cat /etc/redhat-release)
    if [ "${VERSION:0:6}" = CentOS ]
    then
        REL=${VERSION#* }
        REL=${REL#* }
        REL=${REL%% *}
        echo "CENTOS$SEP$REL"
        exit 0
    fi
fi

# SLES
if [ -e /etc/SuSE-release ]
then
    # SLES 11
    VERSION=$(sed -rn 's/^VERSION = (.*)/\1/p' < /etc/SuSE-release)
    SP=$(sed -rn 's/^PATCHLEVEL = (.*)/\1/p' < /etc/SuSE-release)
    if [ "$VERSION" = 11 -a "$SP" = 1 ] 
    then
        echo "SLES$SEP${VERSION}SP1"
        exit 0
    elif [ "$VERSION" = 11 ]
        echo "SLES$SEP${VERSION}"
        exit 0
    fi
fi

exit 1
