#!/bin/bash
#
# This script determines the Linux distribution we are running
# on. It output two words: (1) The distro name and (2) the version
# Example output "UBUNTU 10.04"

# Ubuntu is detected with /etc/lsb-release
SEP=${1:- }
if [ -e /etc/lsb-release ]
then
    . /etc/lsb-release
    if [ -n "$DISTRIB_ID" -a -n "$DISTRIB_RELEASE" ] ; then
        echo "${DISTRIB_ID^^*}$SEP$DISTRIB_RELEASE"
        exit 0
    fi
fi

# Debian: We drop the last version: 5.0.4 -> 5.0
if [ -e /etc/debian_version ]
then
    VERSION=$(cat /etc/debian_version)
    if [ "${VERSION:3:1}" = . ] ; then
        VERSION=${VERSION:0:3}
    fi
    if [ "${VERSION:0:6}" = "wheezy" ] ; then
        VERSION="7.0"
    fi
    if [ "${VERSION:0:6}" = "jessie" ] ; then
        VERSION="8.0"
    fi
    echo "DEBIAN$SEP$VERSION"
    exit 0
fi

# RedHat / CentOS
if [ -e /etc/redhat-release ]
then
    # CentOS release 5.4 (Final)
    VERSION=$(cat /etc/redhat-release)
    if [ "${VERSION:0:6}" = CentOS ]
    then
        if [ "${VERSION:0:24}" = "CentOS Linux release 6.0" ]; then
            echo "CENTOS${SEP}6.0"
            exit 0
        elif [ "${VERSION:0:24}" = "CentOS Linux release 7.0" ]; then
            echo "CENTOS${SEP}7.0"
            exit 0
        fi
        REL=${VERSION#* }
        REL=${REL#* }
        REL=${REL%% *}
        echo "CENTOS$SEP$REL"
        exit 0
    elif [ "${VERSION:0:43}" = "Red Hat Enterprise Linux Server release 6.0" ]
    then
        echo "REDHAT${SEP}6.0"
        exit 0
    elif [ "${VERSION:0:43}" = "Red Hat Enterprise Linux Server release 6.1" ]
    then
        echo "REDHAT${SEP}6.1"
        exit 0
    elif [ "${VERSION:0:43}" = "Red Hat Enterprise Linux Server release 6.2" ]
    then
        echo "REDHAT${SEP}6.2"
        exit 0
    elif [ "${VERSION:0:43}" = "Red Hat Enterprise Linux Server release 6.3" ]
    then
        echo "REDHAT${SEP}6.3"
        exit 0
    elif [ "${VERSION:0:43}" = "Red Hat Enterprise Linux Server release 6.4" ]
    then
        echo "REDHAT${SEP}6.4"
        exit 0
    elif [ "${VERSION:0:43}" = "Red Hat Enterprise Linux Server release 6.5" ]
    then
        echo "REDHAT${SEP}6.5"
        exit 0
    elif [ "${VERSION:0:43}" = "Red Hat Enterprise Linux Server release 7.0" ]
    then
        echo "REDHAT${SEP}7.0"
        exit 0
    fi
fi

# SLES
if [ -e /etc/SuSE-release ]
then
    # SLES 11
    VERSION=$(sed -rn 's/^VERSION = (.*)/\1/p' < /etc/SuSE-release)
    SP=$(sed -rn 's/^PATCHLEVEL = (.*)/\1/p' < /etc/SuSE-release)
    if [ "$VERSION" = 11 -a "$SP" = 1 ] 
    then
        echo "SLES$SEP${VERSION}SP1"
        exit 0
    elif [ "$VERSION" = 11 -a "$SP" = 2 ] 
    then
        echo "SLES$SEP${VERSION}SP2"
        exit 0
    elif [ "$VERSION" = 10 -a "$SP" = 1 ] 
    then
        echo "SLES$SEP${VERSION}SP1"
        exit 0
    elif [ "$VERSION" = 11 -a "$SP" = 3 ] 
    then
        echo "SLES$SEP${VERSION}SP3"
        exit 0
    elif [ "$VERSION" = 10 -a "$SP" = 1 ] 
    then
        echo "SLES$SEP${VERSION}SP1"
        exit 0
    elif [ "$VERSION" = 10 -a "$SP" = 2 ] 
    then
        echo "SLES$SEP${VERSION}SP2"
        exit 0
    elif [ "$VERSION" = 11 ]
    then
        echo "SLES$SEP${VERSION}"
        exit 0
    elif [ "$VERSION" = 12.1 ]
    then
        echo "OPENSUSE$SEP${VERSION}"
        exit 0
    fi
fi

exit 1
