---
- name: Configure mod-gearman feature
  gather_facts: False
  hosts: all
  tasks:
    - name: pretask
      include: pretasks.yml
    - name: GEARMAND_PORT
      set_fact: GEARMAND_PORT="{{ lookup('env', 'GEARMAND_PORT')|default('0.0.0.0:4730', true) }}"
    - name: GEARMAN_SECRET
      set_fact: GEARMAN_SECRET="{{ lookup('env', 'GEARMAN_SECRET')|default('sakuli_secret', true)}}"
    # Preconfig detection commented out, because the Playbook must be able to run
    # multiple times in containerized environments.
    # See https://github.com/ConSol/sakuli/issues/273
    # - name: GEARMAND_ON
    #   shell: grep "CONFIG_MOD_GEARMAN='off'" {{ OMD_ROOT}}/etc/omd/site.conf
    #   register: gearman_grep
    #   ignore_errors: yes
    # - name: Check if mod-gearman is already enabled
    #   fail:
    #     msg: "Mod-Gearman is already enabled on this site. I won't touch anything here..."
    #   when: gearman_grep.rc > 0
    - name: OMD config
      shell: "omd {{ item }}"
      with_items:
        - stop
        - config set GEARMAND on
        - "config set GEARMAND_PORT {{ GEARMAND_PORT }}"
        - config set GEARMAN_NEB on
        - config set MOD_GEARMAN on
    - name: Gearman secret
      lineinfile:
        path: "{{ OMD_ROOT }}/etc/mod-gearman/secret.key"
        regexp: '.*'
        line: "{{ GEARMAN_SECRET }}"
