
- name: Configure screenshot_history feature
  gather_facts: False
  hosts: all
  tasks:
    - name: pretask
      include: pretasks.yml
    - name: sakuli_screenshot_cleanup.sh
      copy:
        src: ./local/bin/sakuli_screenshot_cleanup.sh
        dest: "{{ OMD_ROOT }}/local/bin/"
        mode: 0770
    - name: cron - sakuli_screenshot_cleanup cron
      copy:
        src: ./etc/cron.d/sakuli_screenshot_cleanup
        dest: "{{ OMD_ROOT }}/etc/cron.d/"
    - name: Thruk - Sakuli SSIs
      copy:
        src: "{{ item }}"
        dest: "{{ OMD_ROOT }}/etc/thruk/ssi"
      with_fileglob:
        - ./etc/thruk/ssi/*.ssi
    - name: Thruk - sakuli_action_menu.conf
      copy:
        src: ./etc/thruk/thruk_local.d/sakuli_action_menu.conf
        dest: "{{ OMD_ROOT }}/etc/thruk/thruk_local.d/"
    - name: Apache - sakuli_screenshots.conf
      template:
        src: ./etc/apache/conf.d/sakuli_screenshots.conf.j2
        dest: "{{ OMD_ROOT }}/etc/apache/conf.d/sakuli_screenshots.conf"
