  - job_name: 'promtail'
  
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # scheme defaults to 'http'.
    metrics_path: /metrics

    static_configs:
      - targets: ['127.0.0.1:###CONFIG_LOKI_PROMTAIL_PORT###']
