#
# ports will be overwritten by the influxdb omd config hook
#

# config file version
apiVersion: 1

# see http://docs.grafana.org/administration/provisioning/#datasources
datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://127.0.0.1:9090/###SITE###/prometheus
    isDefault: false
    editable: false
