#!/bin/sh
# Startskript for OMD sites

### BEGIN INIT INFO
# Provides:          omd
# Required-Start:    $remote_fs $syslog $time
# Required-Stop:     $remote_fs $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OMD sites
# Description:       Start and stop the sites of the OpenSource Monitoring 
#                    Distribution (OMD)
### END INIT INFO

# -- don't start omd, if not configured in /etc/default/omd
AUTOSTART=0

[ -r /etc/default/omd ] && . /etc/default/omd

case "$1" in
    start)
	if [ "$AUTOSTART" = "1" ]; then
          echo "Starting all OMD monitoring sites:"
          /usr/bin/omd "$1"
	else
	  echo "OMD autostart disabled, skipping ..."
	fi
    ;;
    stop)
        echo "Stopping all OMD monitoring sites:"
        /usr/bin/omd "$1"
    ;;
    restart)
        echo "Restarting all OMD monitoring sites:"
        /usr/bin/omd "$1"
    ;;
    reload)
        echo "Reloading all OMD monitoring sites:"
        /usr/bin/omd "$1"
    ;;
    status)
        echo "Checking state of all OMD monitoring sites:"
        /usr/bin/omd "$1"
    ;;
    *)
        echo "Doing $1 on all OMD monitoring sites:"
        /usr/bin/omd "$1"
    ;;
esac


