eeval   [ SITE     	   ] = "$OMD_SITE$"
eeval   [ ROOT     	   ] = "$OMD_ROOT$"
command [ check_nagios	   ] = check_nagios -F $OMD_ROOT$/tmp/nagios/status.dat -e 1 -C $OMD_ROOT$/bin/nagios
command [ tmp_dir	   ] = check_disk -w 20% -c 10% -p $OMD_ROOT$/tmp	
command [ proc_nagios_inst ] = check_procs -w :50 -c 1: -C nagios -a '$OMD_ROOT$/bin/nagios -d $OMD_ROOT$/tmp/nagios/nagios.cfg'
command [ proc_nagios_rss  ] = check_procs -w 100000 -c 200000 -C nagios -a '$OMD_ROOT$/bin/nagios -d $OMD_ROOT$/tmp/nagios/nagios.cfg' -m RSS
command [ proc_nagios_vsz  ] = check_procs -w 200000 -c 400000 -C nagios -a '$OMD_ROOT$/bin/nagios -d $OMD_ROOT$/tmp/nagios/nagios.cfg' -m VSZ
command [ proc_nagios_cpu  ] = check_procs -w 80 -c 90 -C nagios -a '$OMD_ROOT$/bin/nagios -d $OMD_ROOT$/tmp/nagios/nagios.cfg' -m CPU
command [ checkresults_dir ] = check_file_age -w 300 -c 600 -f $OMD_ROOT$/tmp/nagios/checkresults
