# Command line parameters can be overwritten or extented via env
# replace "." with "_" from command line flags and prefix with vmauth_
# Note: the following parameter cannot be overwritten:
# - retentionPeriod, httpListenAddr (from omd config) and
# eg.
# special: default parameter for deduplication

vmauth_loggerLevel=INFO
vmauth_loggerOutput=stdout
vmauth_httpconntimeout=60s

vmauth_auth_config=$OMD_ROOT/etc/victoriametrics/vmauth/auth_conf.yml

# Protect vmauth own endpoints
vmauth_reloadAuthKey=SecretKey
vmauth_flagsAuthKey=SecretKey
#vmauth_metricsAuthKey=SecretKey
vmauth_pprofAuthKey=SecretKey

# Path to files for TLS certificate. Used only if -tls is set. Prefer ECDSA certs instead of RSA certs, since RSA certs are slow
# default; use key from local apache
# if separate server name used, a separate certificate is needed
vmauth_tlsCertFile=$OMD_ROOT/etc/apache/site.cert
vmauth_tlsKeyFile=$OMD_ROOT/etc/apache/site.key
